### ISSUE TITLE
unable to install pysmbc on windows

### ISSUE THREAD

**Issue by dursundiatics** [hamano/pysmbc#59]
I am working on a project which requires pysmbc, I need to install this project on windows 10. while installing pysmbc I get the following error; any help, please;

Collecting pysmbc
  Using cached pysmbc-1.0.23.tar.gz (26 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\LENOVO\AppData\Local\Temp\pip-install-p2tj60wg\pysmbc_e51419d09aff403eb9eca13e53bf1217\setup.py", line 118, in <module>  
          library_dirs=pkgconfig_L("smbclient"),
        File "C:\Users\LENOVO\AppData\Local\Temp\pip-install-p2tj60wg\pysmbc_e51419d09aff403eb9eca13e53bf1217\setup.py", line 68, in pkgconfig_L
          c = subprocess.Popen(["pkg-config", "--libs", pkg], stdout=subprocess.PIPE)
        File "C:\Dev\platforms\python\python39\lib\subprocess.py", line 951, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Dev\platforms\python\python39\lib\subprocess.py", line 1420, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] Sistem belirtilen dosyayı bulamıyor
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by hamano** [comment]
you need pkg-config for windows.
try https://download.gnome.org/binaries/win32/dependencies/
